#!/usr/bin/env bash
#############################################
# Displays a hierarchical list of all currently running processes, for all users.
#############################################


ps auxf
