#!/usr/bin/env bash
#############################################
# Partial immunity to SIGTERM, SIGQUIT, and SIGINT.
#############################################


trap "echo Y U no love me?!" SIGINT
trap 'echo I hate the kill command; kill -3 $$' SIGTERM
trap "rm -f /var/run/myscript.pid; exit 1" SIGQUIT

myPID="$$"
echo "$myPID" > /var/run/myscript.pid


while true
do
	echo "To infinity and beyond"
done
