#!/usr/bin/env bash
#############################################
# An init.d daemon manager simulator.
#############################################


if [ "$1" = start ]
then
	./manage_my_process &
	pid=$(pgrep -f "bash ./manage_my_process")
	echo "$pid" > /var/run/my_process.pid
	echo "manage_my_process started"
elif [ "$1" = stop ]
then
	pid=$(pgrep -f "bash ./manage_my_process")
	kill -9 "$pid"
	sudo rm -f /var/run/my_process.pid
	echo "manage_my_process stopped"
elif [ "$1" = restart ]
then
	pid=$(pgrep -f "bash ./manage_my_process")
	if [ -n "$pid" ]
	then
		kill -9 "$pid"
		sudo rm -f /var/run/my_process.pid
	fi
	./manage_my_process &
	pid=$(pgrep -f "bash ./manage_my_process")
	echo "$pid" > /var/run/my_process.pid
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
