#!/usr/bin/env bash
#############################################
# Displays some text, at two-second intervals, indefinitely.
#############################################


while true
do
	echo "To infinity and beyond"
	sleep 2
done
