#!/usr/bin/env bash
#############################################
# A daemon simulator.
#############################################


while true
do
	echo "I am alive!" >> /tmp/my_process
	sleep 2
done
